version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/start:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenginxnet

  node:
    build:
      context: ./node
    image: thiagofelipeg3/node
    container_name: nodeapp
    volumes:
      - ./node:/var/www/html
      - /var/www/html/node_modules
    networks:
      - nodenginxnet
    ports:
      - "3001:3001"
    depends_on:
      - db


  nginx:
    build:
      context: ./nginx
    image: thiagofelipeg3/nginx
    container_name: nginxproxy
    networks:
      - nodenginxnet
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  nodenginxnet:
    driver: bridge
