version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - nodenginxnet

  node:
    build:
      context: ./node
    image: thiagofelipeg3/node
    container_name: nodeapp
    volumes:
      - ./node:/var/www/html
    networks:
      - nodenginxnet
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    image: thiagofelipeg3/nginx
    container_name: nginxproxy
    networks:
      - nodenginxnet
    ports:
      - "8080:80"

networks:
  nodenginxnet:
    driver: bridge
